import React from 'react'
import { useEffect } from '@storybook/client-api'
import { number } from '@storybook/addon-knobs'
import styles from './pages/demoIcons.module.scss'
import SvgIcon from '../lib/components/icon/SvgIcon'
import demoIcons from './pages/demoIcons'

export default {
  title: 'Robits/Icons'
}

export const icons = () => {
  const widthOptions = {
    range: true,
    min: 1,
    max: 70,
    step: 1
  }
  const width = number('Width', 24, widthOptions)

  // eslint-disable-next-line
  useEffect(() => {
    styles.use()
  }, [])

  return (
    <>
      <p className={styles.locals['grid-caption']}>
        The following (FPO) icons are demo'ed here to showcase the <code>{'<SvgIcon />'}</code>
        custom component, which given a Javascript library source file, as generated by{' '}
        <a href='https://github.com/sumcoding/svg-to-js-cli'>svg-to-js-cli</a>, and a name string,
        renders the SVG inline with configurable props
      </p>
      <div className={styles.locals['icons-grid']}>
        {Object.keys(demoIcons).map((name, index) => {
          return (
            <div key={`svg-icon-${name}-${index}`}>
              <SvgIcon source={demoIcons} name={name} width={width} />
              {name}
            </div>
          )
        })}
      </div>
    </>
  )
}

icons.story = {
  parameters: {
    info: {
      disable: true
    }
  }
}
